//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GamePlan.Application.Resources {
	using System;
	
	
	/// <summary>
	///   Класс ресурса со строгой типизацией для поиска локализованных строк и т.д.
	/// </summary>
	// Этот класс создан автоматически классом StronglyTypedResourceBuilder
	// с помощью такого средства, как ResGen или Visual Studio.
	// Чтобы добавить или удалить член, измените файл .ResX и снова запустите ResGen
	// с параметром /str или перестройте свой проект VS.
	[global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
	[global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
	[global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
	public class ErrorMessage {
		
		private static global::System.Resources.ResourceManager resourceMan;
		
		private static global::System.Globalization.CultureInfo resourceCulture;
		
		[global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
		internal ErrorMessage() {
		}
		
		/// <summary>
		///   Возвращает кэшированный экземпляр ResourceManager, использованный этим классом.
		/// </summary>
		[global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
		public static global::System.Resources.ResourceManager ResourceManager {
			get {
				if (object.ReferenceEquals(resourceMan, null)) {
					global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("FonTech.Application.Resources.ErrorMessage", typeof(ErrorMessage).Assembly);
					resourceMan = temp;
				}
				return resourceMan;
			}
		}
		
		/// <summary>
		///   Перезаписывает свойство CurrentUICulture текущего потока для всех
		///   обращений к ресурсу с помощью этого класса ресурса со строгой типизацией.
		/// </summary>
		[global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
		public static global::System.Globalization.CultureInfo Culture {
			get {
				return resourceCulture;
			}
			set {
				resourceCulture = value;
			}
		}
		
		/// <summary>
		///   Ищет локализованную строку, похожую на Неверный пароль.
		/// </summary>
		public static string IncorrectPassword {
			get {
				return ResourceManager.GetString("IncorrectPassword", resourceCulture);
			}
		}
		
		/// <summary>
		///   Ищет локализованную строку, похожую на Внутренняя ошибка сервера.
		/// </summary>
		public static string InternalServerError {
			get {
				return ResourceManager.GetString("InternalServerError", resourceCulture);
			}
		}
		
		/// <summary>
		///   Ищет локализованную строку, похожую на Некорректный запрос клиента.
		/// </summary>
		public static string InvalidClientRequest {
			get {
				return ResourceManager.GetString("InvalidClientRequest", resourceCulture);
			}
		}
		
		/// <summary>
		///   Ищет локализованную строку, похожую на Некорректный токен.
		/// </summary>
		public static string InvalidToken {
			get {
				return ResourceManager.GetString("InvalidToken", resourceCulture);
			}
		}
		
		/// <summary>
		///   Ищет локализованную строку, похожую на Введенные пароли не совпадают.
		/// </summary>
		public static string PasswordsNotEquals {
			get {
				return ResourceManager.GetString("PasswordsNotEquals", resourceCulture);
			}
		}
		
		/// <summary>
		///   Ищет локализованную строку, похожую на Такой отчёт уже существует.
		/// </summary>
		public static string ReportAlreadyExist {
			get {
				return ResourceManager.GetString("ReportAlreadyExist", resourceCulture);
			}
		}
		
		/// <summary>
		///   Ищет локализованную строку, похожую на Отчёт не найден.
		/// </summary>
		public static string ReportNotFound {
			get {
				return ResourceManager.GetString("ReportNotFound", resourceCulture);
			}
		}
		
		/// <summary>
		///   Ищет локализованную строку, похожую на Отчёты не найдены.
		/// </summary>
		public static string ReportsNotFound {
			get {
				return ResourceManager.GetString("ReportsNotFound", resourceCulture);
			}
		}
		
		/// <summary>
		///   Ищет локализованную строку, похожую на Данная роль уже есть у выбранного пользователя.
		/// </summary>
		public static string RoleAlreadyExists {
			get {
				return ResourceManager.GetString("RoleAlreadyExists", resourceCulture);
			}
		}
		
		/// <summary>
		///   Ищет локализованную строку, похожую на Указанная роль отсутствует.
		/// </summary>
		public static string RoleNotFound {
			get {
				return ResourceManager.GetString("RoleNotFound", resourceCulture);
			}
		}
		
		/// <summary>
		///   Ищет локализованную строку, похожую на Такой пользователь уже существует.
		/// </summary>
		public static string UserAlreadyExists {
			get {
				return ResourceManager.GetString("UserAlreadyExists", resourceCulture);
			}
		}
		
		/// <summary>
		///   Ищет локализованную строку, похожую на Пользователь с такой ролью уже существует.
		/// </summary>
		public static string UserAlreadyExistsWithThisRole {
			get {
				return ResourceManager.GetString("UserAlreadyExistsWithThisRole", resourceCulture);
			}
		}
		
		/// <summary>
		///   Ищет локализованную строку, похожую на Пользователь не найден.
		/// </summary>
		public static string UserNotFound {
			get {
				return ResourceManager.GetString("UserNotFound", resourceCulture);
			}
		}
	}
}
